
###

GET http://localhost:4000/author-api/authors

###

POST  http://localhost:4000/author-api/author
Content-Type: application/json

{
    "userType" : "Author",
    "userName": "Aryashu448",
    "password": "Aryashu448",
    "email" : "aryashu448@gmail.com"
}


###
POST  http://localhost:4000/author-api/login
Content-Type: application/json

{
    "userType" : "Author",
    "userName": "Aryashu448",
    "password": "Aryashu448"
    
}

###Add article by author

POST  http://localhost:4000/author-api/article
Content-Type: application/json

{ 
    "articleId":"{{$timestamp}}",
    "title":"SWEEP",
    "category":"Sustainability",
    "content":"Sweep is an AI-powered waste collection system designed to minimize waste and enhance recycling.It utilizes smart vehicles(Sweepers) with on-board cameras that implement deep learning models to recognize different types of waste materials. These vehicles then utilize robotic techniques to automatically segregate waste into different categories at the point of collection",
    "dateOfCreation":"{{$datetime iso8601}}",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"Aryashu448",
    "comments": [ ],
    "status":true

}


### update article by author

PUT  http://localhost:4000/author-api/article
Content-Type: application/json

{ 
    "articleId":"1710083190",
    "title":"SWEEP",
    "category":"Sustainability",
    "content":"SWEEP is an AI-powered waste collection system designed to minimize waste and enhance recycling.It utilizes smart vehicles(Sweepers) with on-board cameras that implement deep learning models to recognize different types of waste materials. These vehicles then utilize robotic techniques to automatically segregate waste into different categories at the point of collection",
    "dateOfCreation":"2024-03-10T15:06:30.578Z",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"Aryashu448",
    "comments": [ ],
    "status":true

}

### delete article by id
PUT  http://localhost:4000/author-api/article/1710083190
Content-Type: application/json

{ 
    "articleId":"1710083190",
    "title":"SWEEP",
    "category":"Sustainability",
    "content":"SWEEP is an AI-powered waste collection system designed to minimize waste and enhance recycling.It utilizes smart vehicles(Sweepers) with on-board cameras that implement deep learning models to recognize different types of waste materials. These vehicles then utilize robotic techniques to automatically segregate waste into different categories at the point of collection",
    "dateOfCreation":"2024-03-10T15:06:30.578Z",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"Aryashu448",
    "comments": [ ],
    "status":true

}
###get aticles by author name
GET http://localhost:4000/author-api/article/Aryashu448